name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs the workflow when code is pushed to `main`

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get latest version tag from Docker Hub
      run: |
        latest_version=$(curl -s "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/testing-pipeline/tags?page_size=1" | jq -r '.results[0].name')
        echo "Latest version from Docker Hub: $latest_version"
        if [[ "$latest_version" =~ ^v[0-9]+$ ]]; then
          new_version=v$(( ${latest_version:1} + 1 ))
        else
          new_version=v1  # Default starting version
        fi
        echo "New version: $new_version"
        echo "VERSION_TAG=$new_version" >> $GITHUB_ENV

    - name: Build Docker image with incremented tag
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/testing-pipeline:$VERSION_TAG .

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/testing-pipeline:$VERSION_TAG
